### ISSUE TITLE
User reference (@tags, at-tags)

### ISSUE THREAD

**Issue by sitarane** [Trustroots/trustroots#351] opened 2016-05-03 08:33 UTC
I'm aware of the tribe/tag discussion. When implementing that (or before), it would be nice for users to be able to quiclky reference each other in messages, profile fields and anywhere relevant.

Use case 1: Messages ; "Hi, I'm travelling with @myFriend near where you live, would you like to host us?" Right now, refering to users means writing their username (recipient unlikely to go check) or entering the link to their profile (cumbersome to sender and hard to read for recipient).

Use case 2: Profile field; "I live in a flatshare with @Friend1 and @Friend2."

Hypothetical usecase: Profile comments; "Me and @goodFriend stayed at their place of a few days and we found them to be decent people".

**Comment by sitarane** [comment] 2016-05-03 08:34
Can't I label this myself?

**Comment by simison** [comment] 2016-05-03 09:27
Yeah, totally! Dupe of #120 though.

This will come at some point. It's just that it's more of a convenience feature compared to really important stuff like "tribes", "better search", "encouraging more full profiles" or "mobile app", so you gotta wait for it. But I'm a fan of this feature as well. :-)

**Closed by simison** 2016-05-03 09:27 UTC
