### ISSUE TITLE
Notifications doesn't disappear

### ISSUE THREAD

**Issue by JeromeScherer** [Trustroots/trustroots#1606] opened 2020-07-19 17:26 UTC
**Describe the bug**
On menu, messages still have a notification with a red one, but the user who sent me a request doesn't exist anymore when I click on the message. It doesn't goes away. 

**To Reproduce**
1. Go to 'messages'
2. Click on 'the new message'
3. See error "This user isn't a member anymore."
4. When back on the main page, the notification is still here

**Expected behavior**
Don't know what's the best in that case. Seeing the message with ""This user isn't a member anymore." after his message, and when back on main page, no notification anymore ? 

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - Browser Brave
 - Version 1.11.97 Chromium: 84.0.4147.89 (Build officiel) (64 bits)

**Comment by rumwerfer** [comment] 2020-10-14 07:24
Thanks for the report! duplicate of #596

**Closed by rumwerfer** 2020-10-14 07:24 UTC
