### ISSUE TITLE
Profiles for households (not only people!)

### ISSUE THREAD

**Issue by elf-pavlik** [Trustroots/trustroots#292] opened 2015-08-08 10:38 UTC
I would see it very useful that households could also have profiles, since people living in same household can have independent accounts. 

eg. https://www.facebook.com/groups/787026344641460/ (IndieHouse)

Where @fkooman @danohuiginn @Dorotea and others live at different times

So far only Dan has profile https://www.trustroots.org/#!/profile/danohu but he stays to busy to reply to requests. Household / group profile with share access could help here a lot!

@fkooman works on some very relevant projects, let's meet in Berlin - maybe even in IndieHouse to discuss it? http://ideas.trustroots.org/2015/07/30/first-trustroots-collective-berlin-2015/
* https://github.com/fkooman/phubble
* https://github.com/fkooman/indiecert

**Comment by simison** [comment] 2015-08-10 16:14
Cool, thanks!

Duplicate of #122

**Closed** 2015-08-10 17:20 UTC
