### ISSUE TITLE
Find users

### ISSUE THREAD

**Issue by roberts-gh** [Trustroots/trustroots#141] opened 2014-12-29 18:20 UTC
cannot find a specific user profile by searching for the nickname, full/partial name, etc.

**Comment by simison** [comment] 2015-01-07 20:10
That sort of privacy settings are a nightmare to maintain/test/implement, so I'd like to keep away from them for as long as possible. But you're right, that would be quite perfect solution.

**Comment by guaka** [comment] 2015-01-07 21:43
Yeah. If these privacy options don't work exactly as indicated there's no
point having them. I think fine grained privacy options are only a
possibility with a dedicated team of programmers and sysadmins and a 100%
testing coverage for privacy.

**Comment by jancborchardt** [comment] 2015-01-08 11:46
The basic form of it – and I think the point of this discussion – would be having a checkbox next to just the email saying »keep email address private«.

**Comment by simison** [comment] 2015-01-08 11:46
>a checkbox next to just the email saying »keep email address private«.

True, probably quite doable.

**Comment by mrkvon** [comment] 2016-02-21 03:35
After some research and testing i believe name+code@example.com is [gmail specific](https://www.tythewebguy.com/secret-gmail-addresses/) (if the link is what you talk about). i.e. the service i'm using doesn't provide that option. Is it some standard? (link?)

**Comment by chreekat** [comment] 2016-02-22 20:19
No, it's not Gmail-specific.

https://en.wikipedia.org/wiki/Email_address#Sub-addressing

E.g. it works fine for my work address, which is handled by a postfix
system.

**Comment by mrkvon** [comment] 2016-02-22 23:35
Thank you, @chreekat, for the clarification and link.

[Wikipedia](https://en.wikipedia.org/wiki/Email_address#Sub-addressing):

> _Some_ mail services support a tag appended to the local part, such that the modified address is an alias to the unmodified address.

[RFC standard](https://tools.ietf.org/html/rfc5233):

> _On email systems that allow_ for 'subaddressing' or 'detailed
   addressing' (e.g., "ken+sieve@example.org"), it is sometimes
   desirable to ...

From these texts it seems that email services don't have to support subaddressing. i.e. the email service i use doesn't receive emails with subaddress. I discourage from using this feature as the only guarantee of the search security. There were other options discussed here which may be preferable.

**Comment by simison** [comment] 2016-02-22 23:47
It's fine guys, thanks. :-) I think it's safest to stay away from email search as it has little benefits and possibly issues we can't foresee.

**Comment by simison** [comment] 2017-07-17 10:17
Closing as duplicate of #530, follow ups there.

**Closed as completed** 2018-06-19 15:35 UTC
Labels: enhancement
