### ISSUE TITLE
can't scroll up with long 1st message

### ISSUE THREAD

**Issue by guaka** [Trustroots/trustroots#172] opened 2015-01-07 11:47 UTC
can't scroll up with long 1st message, both when reading and writing
![screen shot 2015-01-07 at 12 47 28](https://cloud.githubusercontent.com/assets/54728/5645096/5c8b247a-966b-11e4-842c-e540b3e89f53.png)

**Comment by guaka** [comment] 2015-01-07 11:47
![screen shot 2015-01-07 at 12 47 28](https://cloud.githubusercontent.com/assets/54728/5645096/5c8b247a-966b-11e4-842c-e540b3e89f53.png)

**Comment by simison** [comment] 2015-01-07 12:11
Just for the record: are you scrolling with mouse scroll or touch pad?

**Comment by guaka** [comment] 2015-01-07 12:14
Touch pad, both in FF and Chrome

**Comment by guaka** [comment] 2015-01-11 20:58
Only now realized that there's a scrollbar that lets me scroll up.
![screen shot 2015-01-11 at 21 57 11](https://cloud.githubusercontent.com/assets/54728/5696787/db446032-99dc-11e4-82a3-6fcce3e0ce67.png)

**Comment by simison** [comment] 2015-01-11 21:32
Nice screenshot!

**Comment by chmac** [comment] 2015-01-13 14:33
Is this a duplicate of #63?

**Comment by guaka** [comment] 2015-01-13 15:31
it is a duplicate now that I changed the title of that issue into "Scroll problems on messages view" :)

**Closed** 2015-04-12 11:33 UTC
Labels: bug, Module:Messages
