### ISSUE TITLE
Welcome Emails get resent when changing email adress

### ISSUE THREAD

**Issue by putzenpu** [Trustroots/trustroots#1484] opened 2020-05-23 10:13 UTC
**Describe the bug**
When changing my email adress on Trustroots, after confirming I received both welcome emails again ("Welcome to trustroots, <name>!" and "Meet new people at trustroots <name>")

**To Reproduce**
1. Go to your profile, change email adress, and confirm change
2. Check inbox of the new email adress for the next few days

**Comment by rumwerfer** [comment] 2020-05-23 10:56
Thanks for the report! Duplicate of #880

**Closed** 2021-03-08 10:05 UTC
